query eventWithNav {
  pageConnection {
    edges {
      node {
        id
        title
        navtitle
        _sys {
          filename
        }
      }
    }
  }
  events(relativePath: "event.mdx") {
    ...EventsParts
  }
}
