query eventWithNav {
  general(relativePath: "general.mdx") {
    order {
      page {
        ... on Document {
          _sys {
            filename
          }
        }
        ... on Page {
          title
        }
      }
      navname
    }
    fav
  }
  events(relativePath: "event.mdx") {
    ...EventsParts
  }
}
