query pageWithNav($relativePath: String!) {
  general(relativePath: "general.mdx") {
    order {
      page {
        ... on Document {
          _sys {
            filename
          }
        }
        ... on Page {
          title
        }
      }
      navname
    }
    fav
  }
  page(relativePath: $relativePath) {
    ...PageParts
  }
}